version: '3.1'
services:
  postgres:
    image:                postgres:9.6
    container_name:       postgres-federation
    restart:              unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./scripts/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      - POSTGRES_USER=${FEDERATION_USER}
      - POSTGRES_PASSWORD=${FEDERATION_PASSWORD}
      - POSTGRES_DB=${FEDERATION_DB:-8800}

  pgadmin:
    image:                dpage/pgadmin4
    container_name:       pgadmin4
    restart:              unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_PORT=${PGADMIN_PORT:-8800}
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:65001
        tag: "catcat-fed-pgadmin"

  federation-service:
    container_name:       catcat-federation-service
    build:
      context:            .
      dockerfile:         Dockerfile
    env_file:             .env
    restart:              unless-stopped
    environment:
      - PORT=${PORT}
    image:                catcatio/catcat-cloud
    working_dir:          /usr/app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    command: npm run dev:docker


